name: Build
on: workflow_dispatch
jobs:
 print-out:
  runs-on: ubuntu-22.04
  steps:
   - name: print env details
     run: env | sort
 Build:
  runs-on: ubuntu-22.04
  needs: print-out
  steps:
   - name: Checkout
     uses: actions/checkout@v4    
   - name: Setup node
     uses: actions/setup-node@v3
     with:
      node-version: 16.13.x
   - name: Install
     run: npm ci
    
