name: Deploy
on: 
  workflow_run:
    workflows: [Build]
    types:
        - completed
jobs: 
  Deploy:
    runs-on: ubuntu-22.04
    steps:
     - name: print env
       run: env | sort
     - name: job complete
       run: echo "clean up done."